version: 1.0.0

# GO SDK使用的客户端部分。
client:
  # 客户端所属的组织，必须是organizations定义的组织
  organization: OrgAHospital
  # 日志级别
  logging:
    level: info
  # MSP证书的根路径
  cryptoconfig:
    # path: ../crypto-config
    path: C:\Users\BUAA\Code\Trusted-Sharing-of-Data-Resources\fabric-deployment\crypto-config

  tlsCerts:
    systemCertPool: true
    client:
      keyfile: C:\Users\BUAA\Code\Trusted-Sharing-of-Data-Resources\fabric-deployment\crypto-config\peerOrganizations\AHospital.trustchain.com\users\Admin@AHospital.trustchain.com\tls\client.key
      certfile: C:\Users\BUAA\Code\Trusted-Sharing-of-Data-Resources\fabric-deployment\crypto-config\peerOrganizations\AHospital.trustchain.com\users\Admin@AHospital.trustchain.com\tls\client.crt
      

# 通道定义
channels:
  medicinechannel:
    orderers:
      - orderer1.trustchain.com
    peers:
      peer0.AHospital.trustchain.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      # peer0.FJMPT.trustchain.com:
      #   endorsingPeer: true
      #   chaincodeQuery: true
      #   ledgerQuery: true
      #   eventSource: true

# 组织配置
organizations:
  OrgAHospital:
    mspid: AHospitalMSP
    cryptoPath: peerOrganizations/AHospital.trustchain.com/users/{username}@AHospital.trustchain.com/msp
    peers:
      - peer0.AHospital.trustchain.com
  # OrgBHospital:
  #   mspid: "BHospitalMSP"
  #   cryptoPath: peerOrganizations/BHospital.trustchain.com/users/{username}@BHospital.trustchain.com/msp
  #   peers:
  #     - peer0.BHospital.trustchain.com
  # OrgFJMPT:
  #   mspid: "FJMPTMSP"
  #   cryptoPath: peerOrganizations/FJMPT.trustchain.com/users/{username}@FJMPT.trustchain.com/msp
  #   peers:
  #     - peer0.FJMPT.trustchain.com
  # OrgAZWDT:
  #   mspid: "AZWDTMSP"
  #   cryptoPath: peerOrganizations/AZWDT.trustchain.com/users/{username}@AZWDT.trustchain.com/msp
  #   peers:
  #     - peer0.AZWDT.trustchain.com
    
    
# orderer节点列表
orderers:
  orderer1.trustchain.com:
    url: 192.168.8.112:7050
    # 传递给gRPC客户端构造函数
    grpcOptions:
      ssl-target-name-override: orderer1.trustchain.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true

# peers节点列表
peers:
  # peer节点定义，可以定义多个
  peer0.AHospital.trustchain.com:
    # URL用于发送背书和查询请求
    url: grpcs://192.168.8.225:7051
    # url: 192.168.8.225:7051
    # 传递给gRPC客户端构造函数
    grpcOptions:
      ssl-target-name-override: peer0.AHospital.trustchain.com
      keep-alive-time: 1000s
      keep-alive-timeout: 20s
      keep-alive-permit: 
      fail-fast: false
      allow-insecure: true
    
    tlsCACerts:
      path: C:\Users\BUAA\Code\Trusted-Sharing-of-Data-Resources\fabric-deployment\crypto-config\peerOrganizations\AHospital.trustchain.com\tlsca\tlsca.AHospital.trustchain.com-cert.pem
  peer0.BHospital.trustchain.com:
    url: 192.168.8.241:7051
    grpcOptions:
      ssl-target-name-override: peer0.BHospital.trustchain.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer0.FJMPT.trustchain.com:
    url: 192.168.8.96:7051
    grpcOptions:
      ssl-target-name-override: peer0.FJMPT.trustchain.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer0.AZWDT.trustchain.com:
    url: 192.168.8.94:7051
    grpcOptions:
      ssl-target-name-override: peer0.AZWDT.trustchain.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true

entityMatchers:
  peer:
    - pattern: (\w*)peer0.AHospital.trustchain.com(\w*)
      urlSubstitutionExp: grpc://192.168.8.225:7051
      sslTargetOverrideUrlSubstitutionExp: peer0.AHospital.trustchain.com
      mappedHost: peer0.AHospital.trustchain.com

  orderer:
    - pattern: (\w*)orderer.example.com(\w*)
      urlsubstitutionexp: 192.168.8.112:7050
      ssltargetoverrideurlsubstitutionexp: orderer.example.com
      mappedhost: orderer.example.com