NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.FJMPT.trustchain.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.FJMPT.trustchain.com-cert.pem
    OrganizationalUnitIdentifier: peer
